services:
  - type: web
    name: gestora-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gestora-db
          property: connectionString
      - key: ADMIN_USERNAME
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ENABLE_SWAGGER
        value: "true"
    healthCheckPath: /actuator/health
    domains:
      - gestora-api.onrender.com

databases:
  - name: gestora-db
    databaseName: gestora_db
    user: gestora_user
    plan: free
    ipAllowList: []  # permite apenas conex√µes internas